mkdir send2World_Imagery_Wayback
xcopy *.py send2World_Imagery_Wayback
xcopy README.md send2World_Imagery_Wayback
xcopy metadata.txt send2World_Imagery_Wayback
zip -r send2World_Imagery_Wayback.zip send2World_Imagery_Wayback
del /Q send2World_Imagery_Wayback
rd send2World_Imagery_Wayback
